#!/bin/bash
#
# Copyright (c) 2020 by Matthew Jacob
# All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of The version 2 GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#
# Matthew Jacob
# Feral Software
# 253 Lowell Street
# Redwood City, CA 94062
# USA
#
# gpl at feral com
#
TDIR=$(mktemp -d)
LIST=$(mktemp)
TAG_LIST=${TAG_LIST-./TAG_LIST}
PATH=${HOME}/bin:$PATH
function usage
{
 echo "usage: $(basename $0) [ndirs]"
 exit 1
}

limit=1
if [[ $# -eq 1 ]]; then
 case $1 in
 [1-9]*) limit=$1;;
 *) usage;;
 esac
elif [[ $# -ne 0 ]]; then
 usage
fi

set -e
STABLE_REPO=${STABLE_REPO:-/remrepos/linux-3.0.y}
if [[ ! -d $STABLE_REPO ]]; then
 echo "repo $STABLE_REPO not found"
 exit 1
fi
if [[ ! -f $TAG_LIST ]]; then
 echo "tag list $TAG_LIST not found"
 exit 1
fi

#
# Update stable linux and git the list of tags
#
topdir=$(pwd)
for tag in $(cat TAG_LIST); do
 dfree=$(/bin/df .|tail -1|awk ' { print $5 }'|sed 's/%//')
 if [[ $dfree -gt 97 ]]; then
  echo Filesystem too full at ${dfree}%
  break
 fi
 [[ -f $tag/.holdme ]] && continue
 echo $tag
 #
 # Clone into new tag
 #
 git clone -q -s $STABLE_REPO $tag
 pushd $tag > /dev/null
 git checkout $tag > /dev/null 2>&1
 ds=$(git log -n 1 --pretty=format:%aD)
 touch --date="$ds" .holdme
 rm -rf .git
 touch -r .holdme .
 popd > /dev/null
 if [[ $((--limit)) -le 0 ]]; then
  break
 fi
done
